server:
  port: 8081
  servlet:
    context-path: /luckymoney
limit:
  minMoney: 1
  maxMoney: 9999
  description: 最少发${limit.minMoney}元,最多发${limit.maxMoney}
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/luckymoney?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true